app_name: Bocal
hide_footer: false
devices:
  - iMac
  - Keyboard
  - Mouse
  - Building
  - Pedago
  - Other
hosts:
  - building
  - general
  - other
  - 1-a-1
  - 1-a-2
  - 1-a-3
  - 1-a-4
  - 1-a-5
  - 1-a-6
  - 1-a-7
  - 1-a-8
  - 1-a-9
  - 1-a-10
  - 1-a-11
  - 1-a-12
  - 1-a-13
  - 1-a-14
  - 1-a-15
  - 1-a-16
  - 1-a-17
  - 1-a-18
  - 1-a-19
  - 1-a-20
  - 1-a-21
  - 1-a-22
  - 1-a-23
  - 1-a-24
  - 1-a-25
  - 1-a-26
  - 1-a-27
  - 1-a-28
  - 1-a-29
  - 1-a-30
  - 1-a-31
  - 1-a-32
  - 1-b-1
  - 1-b-2
  - 1-b-3
  - 1-b-4
  - 1-b-5
  - 1-b-6
  - 1-b-7
  - 1-b-8
  - 1-b-9
  - 1-b-11
  - 1-b-12
  - 1-b-13
  - 1-b-14
  - 1-b-15
  - 1-b-16
  - 1-b-17
  - 1-b-18
  - 1-b-19
  - 1-b-21
  - 1-b-23
  - 1-b-24
  - 1-b-25
  - 1-b-26
  - 1-b-27
  - 1-b-28
  - 1-b-29
  - 1-b-30
  - 1-b-31
  - 1-b-32
  - 1-c-1
  - 1-c-2
  - 1-c-3
  - 1-c-4
  - 1-c-5
  - 1-c-6
  - 1-c-7
  - 1-c-8
  - 1-c-9
  - 1-c-10
  - 1-c-11
  - 1-c-12
  - 1-c-13
  - 1-c-14
  - 1-c-15
  - 1-c-16
  - 1-c-17
  - 1-c-18
  - 1-c-19
  - 1-c-20
  - 1-c-21
  - 1-c-22
  - 1-c-23
  - 1-c-24
  - 1-c-25
  - 1-c-26
  - 1-c-27
  - 1-c-28
  - 1-c-29
  - 1-c-30
  - 1-c-31
  - 1-c-32
  - 1-d-1
  - 1-d-2
  - 1-d-3
  - 1-d-4
  - 1-d-5
  - 1-d-6
  - 1-d-7
  - 1-d-8
  - 1-d-9
  - 1-d-11
  - 1-d-12
  - 1-d-13
  - 1-d-14
  - 1-d-15
  - 1-d-16
  - 1-d-17
  - 1-d-18
  - 1-d-19
  - 1-d-20
  - 1-d-21
  - 1-d-23
  - 1-d-24
  - 1-d-25
  - 1-d-26
  - 1-d-27
  - 1-d-28
  - 1-d-29
  - 1-d-30
  - 1-d-31
  - 1-d-32
  - 1-e-1
  - 1-e-2
  - 1-e-3
  - 1-e-4
  - 1-e-5
  - 1-e-6
  - 1-e-7
  - 1-e-8
  - 1-e-9
  - 1-e-10
  - 1-e-11
  - 1-e-12
  - 1-e-13
  - 1-e-14
  - 1-e-15
  - 1-e-16
  - 1-e-17
  - 1-e-18
  - 1-e-19
  - 1-e-20
  - 1-e-21
  - 1-e-22
  - 1-e-23
  - 1-e-24
  - 1-e-25
  - 1-e-26
  - 1-e-27
  - 1-e-28
  - 1-e-29
  - 1-e-30
  - 1-e-31
  - 1-e-32
  - 2-a-1
  - 2-a-2
  - 2-a-3
  - 2-a-4
  - 2-a-5
  - 2-a-6
  - 2-a-7
  - 2-b-1
  - 2-b-2
  - 2-b-3
  - 2-b-4
  - 2-b-5
  - 2-b-6
  - 2-b-7
  - 2-b-8
  - 2-b-9
  - 2-c-1
  - 2-c-2
  - 2-c-3
  - 2-c-4
  - 2-c-5
  - 2-c-6
  - 2-c-7
  - 2-c-8
  - 2-c-9
  - 2-d-1
  - 2-d-2
  - 2-d-3
  - 2-d-4
  - 2-d-5
  - 2-d-6
  - 2-d-7
  - 2-d-8
  - 2-d-9
  - 2-e-1
  - 2-e-2
  - 2-e-3
  - 2-e-4
  - 2-e-5
  - 2-e-6
  - 2-e-7
  - 2-e-8
  - 2-e-9
  - 2-f-1
  - 2-f-2
  - 2-f-3
  - 2-f-4
  - 2-f-5
  - 2-f-6
  - 2-f-7
  - 2-f-8
  - 2-f-9
  - 2-g-1
  - 2-g-2
  - 2-g-3
  - 2-g-4
  - 2-g-5
  - 2-g-6
  - 2-g-7
  - 2-g-8
  - 2-g-9
  - 2-h-1
  - 2-h-2
  - 2-h-3
  - 2-h-4
  - 2-h-5
  - 2-h-6
  - 2-h-7
  - 2-h-8
  - 2-h-9
  - 2-i-1
  - 2-i-2
  - 2-i-3
  - 2-i-4
  - 2-i-5
  - 2-i-6
  - 2-i-7
  - 3-a-1
  - 3-a-2
  - 3-a-3
  - 3-a-4
  - 3-a-5
  - 3-a-6
  - 3-a-7
  - 3-a-8
  - 3-a-9
  - 3-a-10
  - 3-a-11
  - 3-a-12
  - 3-a-13
  - 3-a-14
  - 3-a-15
  - 3-a-16
  - 3-a-17
  - 3-a-18
  - 3-a-19
  - 3-a-20
  - 3-a-21
  - 3-a-22
  - 3-a-23
  - 3-a-24
  - 3-a-25
  - 3-b-1
  - 3-b-2
  - 3-b-3
  - 3-b-4
  - 3-b-5
  - 3-b-6
  - 3-b-7
  - 3-b-8
  - 3-b-9
  - 3-b-10
  - 3-b-11
  - 3-b-12
  - 3-b-13
  - 3-c-1
  - 3-c-2
  - 3-c-3
  - 3-c-4
  - 3-c-5
  - 3-c-6
  - 3-c-7
  - 3-c-8
  - 3-c-9
  - 3-c-10
  - 3-c-11
  - 3-c-12
  - 3-d-1
  - 3-d-2
  - 3-d-3
  - 3-d-4
  - 3-d-5
  - 3-d-6
  - 3-d-7
  - 3-d-8
  - 3-d-9
  - 3-d-10
  - 3-d-11
  - 3-d-12
  - 3-d-13
  - 3-e-1
  - 3-e-2
  - 3-e-3
  - 3-e-4
  - 3-e-5
  - 3-e-6
  - 3-e-7
  - 3-e-8
  - 3-e-9
  - 3-e-10
  - 3-e-11
  - 3-e-12
  - 3-e-13
  - 3-e-14
  - 3-e-15
  - 3-e-16
  - 3-e-17
  - 3-e-18
  - 3-e-19
  - 3-e-20
  - 3-e-21
  - 3-e-22
  - 3-e-23
  - 3-e-24
  - 3-e-25
  - 3-e-26
  - 3-e-27
  - 3-e-28
  - 3-e-29
  - 3-e-30
  - 3-f-1
  - 3-f-2
  - 3-f-3
  - 3-f-4
  - 3-f-5
  - 3-f-6
  - 3-f-7
  - 3-f-8
  - 3-f-9
  - 3-f-10
  - 3-f-11
  - 3-f-12
  - 3-f-13
  - 3-g-1
  - 3-g-2
  - 3-g-3
  - 3-g-4
  - 3-g-5
  - 3-g-6
  - 3-g-7
  - 3-g-8
  - 3-g-9
  - 3-g-10
  - 3-h-1
  - 3-h-2
  - 3-h-3
  - 3-h-4
  - 3-h-5
  - 3-h-6
  - 3-h-7
  - 3-h-8
  - 3-i-1
  - 3-i-2
  - 3-i-3
  - 3-i-4
  - 3-i-5
